In [1]:
import torch

In [2]:
input_tensor = torch.tensor([[1, 2, 3, 3], [1, 2, 2, 3], [1, 1, 2, 2]])
pad_idx = 3

In [3]:
mask = (input_tensor != pad_idx).float()

In [4]:
mask

tensor([[1., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])

In [5]:
mask.masked_fill_(mask.logical_not(), float('-inf'))

tensor([[1., 1., -inf, -inf],
        [1., 1., 1., -inf],
        [1., 1., 1., 1.]])

In [6]:
mask.masked_fill_(mask == 1, 0)

tensor([[0., 0., -inf, -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., 0.]])

In [10]:
mask.unsqueeze(1).unsqueeze(2).repeat(1, 2, 2, 1)

tensor([[[[0., 0., -inf, -inf],
          [0., 0., -inf, -inf]],

         [[0., 0., -inf, -inf],
          [0., 0., -inf, -inf]]],


        [[[0., 0., 0., -inf],
          [0., 0., 0., -inf]],

         [[0., 0., 0., -inf],
          [0., 0., 0., -inf]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])