In [1]:
import torch

In [2]:
import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "../")))

In [3]:
from utils.tokenizer import prepare_tokenizer, pad_tensor

In [4]:
vocab, eos_idx, bos_idx, pad_idx, answer_pad_idx, vocab_size = prepare_tokenizer()

In [5]:
test_len = 7
test_t_1d = torch.tensor([1, 1, 1, 1])
test_t_1d_short = torch.tensor([1, 1])
test_t_2d = torch.tensor([[1, 1, 1, 1], [1, 1, 1, 1]])
test_t_2d_short = torch.tensor([[1, 1], [1, 1]])

In [6]:
print(f"eos_idx: {eos_idx}, bos_idx: {bos_idx}, pad_idx: {pad_idx}, answer_pad_idx: {answer_pad_idx}")

eos_idx: 8000, bos_idx: 8001, pad_idx: 8002, answer_pad_idx: 8003


In [7]:
pad_tensor(test_t_1d, test_len, eos_idx, bos_idx, pad_idx)

tensor([8001,    1,    1,    1,    1, 8000, 8002])

In [8]:
pad_tensor(test_t_1d_short, test_len, eos_idx, bos_idx, answer_pad_idx)

tensor([8001,    1,    1, 8000, 8003, 8003, 8003])

In [9]:
pad_tensor(test_t_2d, test_len, eos_idx, bos_idx, pad_idx)

tensor([[8001,    1,    1,    1,    1, 8000, 8002],
        [8001,    1,    1,    1,    1, 8000, 8002]])

In [10]:
pad_tensor(test_t_2d_short, test_len, eos_idx, bos_idx, answer_pad_idx)

tensor([[8001,    1,    1, 8000, 8003, 8003, 8003],
        [8001,    1,    1, 8000, 8003, 8003, 8003]])

In [11]:
test_t_1d_too_long = torch.randint(0, 1, (test_len + 1,))
test_t_2d_too_long = torch.randint(0, 1, (test_len + 1, test_len + 1))

In [12]:
pad_tensor(test_t_1d_too_long, test_len, eos_idx, bos_idx, pad_idx)

tensor([8001,    0,    0,    0,    0,    0, 8000])

In [13]:
pad_tensor(test_t_2d_too_long, test_len, eos_idx, bos_idx, answer_pad_idx)

tensor([[8001,    0,    0,    0,    0,    0, 8000],
        [8001,    0,    0,    0,    0,    0, 8000],
        [8001,    0,    0,    0,    0,    0, 8000],
        [8001,    0,    0,    0,    0,    0, 8000],
        [8001,    0,    0,    0,    0,    0, 8000],
        [8001,    0,    0,    0,    0,    0, 8000],
        [8001,    0,    0,    0,    0,    0, 8000],
        [8001,    0,    0,    0,    0,    0, 8000]])

In [14]:
import torch
from torch.utils.data import DataLoader

In [15]:
from utils.load_data import load_data, prep_dolly_collate_fn, prep_squad_collate_fn

In [16]:
qc_len = 512 + 256
a_len = 100

In [17]:
squad_collate = prep_squad_collate_fn(qc_len, a_len, eos_idx, bos_idx, pad_idx, answer_pad_idx, pad_tensor)

In [18]:
squad, dolly = load_data()

In [19]:
batch_size = 2

In [20]:
squadDataloader = DataLoader(squad, batch_size=batch_size, shuffle=True, collate_fn=squad_collate)

In [21]:
for batch in squadDataloader:
    break

In [23]:
qc, a = batch

In [24]:
qc.shape

torch.Size([2, 768])

In [25]:
a.shape

torch.Size([2, 100])