In [1]:
import torch

In [2]:
pad_idx = -1

In [3]:
test_input = torch.tensor([[1, 2, -1, -1], [5, 6, 7, -1], [9, 10, 11, 12]])

In [13]:
batch_size, seq_len = test_input.size()

In [6]:
attn_mask = (test_input != pad_idx).float()

In [7]:
attn_mask

tensor([[1., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])

In [8]:
attn_mask.masked_fill_(attn_mask.logical_not(), float('-inf'))

tensor([[1., 1., -inf, -inf],
        [1., 1., 1., -inf],
        [1., 1., 1., 1.]])

In [9]:
attn_mask

tensor([[1., 1., -inf, -inf],
        [1., 1., 1., -inf],
        [1., 1., 1., 1.]])

In [10]:
num_heads = 2

In [11]:
attn_mask.masked_fill_(attn_mask == 1, 0)

tensor([[0., 0., -inf, -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., 0.]])

In [12]:
attn_mask

tensor([[0., 0., -inf, -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., 0.]])

In [14]:
attn_mask = attn_mask.unsqueeze(1).unsqueeze(2).repeat(1, num_heads, seq_len, 1)

In [16]:
attn_mask.shape

torch.Size([3, 2, 4, 4])

In [17]:
attn_mask[0]

tensor([[[0., 0., -inf, -inf],
         [0., 0., -inf, -inf],
         [0., 0., -inf, -inf],
         [0., 0., -inf, -inf]],

        [[0., 0., -inf, -inf],
         [0., 0., -inf, -inf],
         [0., 0., -inf, -inf],
         [0., 0., -inf, -inf]]])