In [5]:
import torch

In [6]:
transition_matrix1 = torch.tensor(
    [
        [0, 0.8, 0.1, 0.1],
        [0, 0, 0.8, 0.2],
        [0, 0, 0, 1],
        [0, 0, 0, 0]
    ]
)
emission_matrix1 = torch.tensor(
    [
        [0.9, 0.1, 0, 0],
        [0, 0.8, 0.2, 0],
        [0, 0, 0.9, 0.1],
        [0, 0.3, 0, 0.7]
    ]
)
targets = torch.tensor([0, 1, 2, 3])
target_lens = torch.tensor([4])
vertex_lens = torch.tensor([4])
expected_answer1 = torch.tensor(
    [
        transition_matrix1[0][1],
        transition_matrix1[1][2],
        transition_matrix1[2][3],
        emission_matrix1[0][0],
        emission_matrix1[1][1],
        emission_matrix1[2][2],
        emission_matrix1[3][3]
    ]
)
expected_answer1 = torch.prod(expected_answer1)

In [7]:
transition_matrix2 = torch.tensor(
    [
        [0, 0.8, 0, 0.2],
        [0, 0.3, 0.6, 0.1],
        [0, 0, 0, 1],
        [0, 0, 0, 0]
    ]
)
emission_matrix2 = torch.tensor(
    [
        [0.5, 0, 0.5, 0],
        [0, 0.8, 0.2, 0],
        [0, 0, 0.9, 0.1],
        [0, 0.1, 0, 0.9]
    ]
)
targets2 = torch.tensor([0, 1, 2, 3])
target_lens = torch.tensor([4])
vertex_lens = torch.tensor([4])
expected_answer2 = torch.tensor(
    [
        transition_matrix2[0][1],
        transition_matrix2[1][2],
        transition_matrix2[2][3],
        emission_matrix2[0][0],
        emission_matrix2[1][1],
        emission_matrix2[2][2],
        emission_matrix2[3][3]
    ]
)
expected_answer2 = torch.prod(expected_answer2)

In [10]:
transition_matrices = torch.stack([transition_matrix1, transition_matrix2])
emission_matrices = torch.stack([emission_matrix1, emission_matrix2])
targets = torch.stack([targets, targets2])

In [13]:
batch, vertex, _ = transition_matrices.shape
_, m = targets.shape

In [14]:
dp = torch.zeros(batch, m, vertex)

In [19]:
bos_idx = 0

In [20]:
dp[:, 0, 0] = emission_matrices[:, 0, bos_idx]

In [21]:
dp

tensor([[[0.9000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.5000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]]])

In [22]:
dp[:, 0, :]

tensor([[0.9000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.0000, 0.0000, 0.0000]])

In [23]:
transition_matrices

tensor([[[0.0000, 0.8000, 0.1000, 0.1000],
         [0.0000, 0.0000, 0.8000, 0.2000],
         [0.0000, 0.0000, 0.0000, 1.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.8000, 0.0000, 0.2000],
         [0.0000, 0.3000, 0.6000, 0.1000],
         [0.0000, 0.0000, 0.0000, 1.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]]])

In [24]:
dp[:, 0, :] @ transition_matrices

tensor([[[0.0000, 0.7200, 0.0900, 0.0900],
         [0.0000, 0.4000, 0.0500, 0.0500]],

        [[0.0000, 0.7200, 0.0000, 0.1800],
         [0.0000, 0.4000, 0.0000, 0.1000]]])