In [27]:
import torch

In [28]:
batch_size, num_vertices = 2, 3

In [29]:
transition_matrix = torch.randn(batch_size, num_vertices, num_vertices)

In [30]:
from utils.fix_probs import acyclic_mask, padding_transition_mask

In [31]:
vertex_lens = torch.tensor([2, 3])

In [32]:
a_mask = acyclic_mask(transition_matrix)
p_mask = padding_transition_mask(transition_matrix, vertex_lens)

In [33]:
transition_matrix = torch.nn.functional.log_softmax(transition_matrix, dim=-1)

In [34]:
transition_matrix

tensor([[[-3.5550, -0.3103, -1.4346],
         [-0.5832, -1.1178, -2.1639],
         [-0.3540, -1.8682, -1.9396]],

        [[-0.9975, -0.5853, -2.6004],
         [-0.3650, -2.2395, -1.6131],
         [-1.1910, -1.1415, -0.9762]]])

In [35]:
a_mask, p_mask

(tensor([[1., 0., 0.],
         [1., 1., 0.],
         [1., 1., 1.]]),
 tensor([[[0., 0., 1.],
          [0., 0., 1.],
          [0., 0., 1.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]))

In [36]:
mask = a_mask + p_mask

In [37]:
mask

tensor([[[1., 0., 1.],
         [1., 1., 1.],
         [1., 1., 2.]],

        [[1., 0., 0.],
         [1., 1., 0.],
         [1., 1., 1.]]])

In [38]:
special = torch.zeros(num_vertices, num_vertices)

In [39]:
special

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [40]:
special.diagonal(offset=1).fill_(1)

tensor([1., 1.])

In [41]:
special

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])

In [42]:
mask.masked_fill_(special == 1, 0)

tensor([[[1., 0., 1.],
         [1., 1., 0.],
         [1., 1., 2.]],

        [[1., 0., 0.],
         [1., 1., 0.],
         [1., 1., 1.]]])

In [43]:
mask

tensor([[[1., 0., 1.],
         [1., 1., 0.],
         [1., 1., 2.]],

        [[1., 0., 0.],
         [1., 1., 0.],
         [1., 1., 1.]]])

In [46]:
transition_matrix

tensor([[[-3.5550, -0.3103, -1.4346],
         [-0.5832, -1.1178, -2.1639],
         [-0.3540, -1.8682, -1.9396]],

        [[-0.9975, -0.5853, -2.6004],
         [-0.3650, -2.2395, -1.6131],
         [-1.1910, -1.1415, -0.9762]]])

In [45]:
# sum elements in transition matrix where mask is not 0
transition_matrix.masked_select(mask != 0)

tensor([-3.5550, -1.4346, -0.5832, -1.1178, -0.3540, -1.8682, -1.9396, -0.9975,
        -0.3650, -2.2395, -1.1910, -1.1415, -0.9762])

In [47]:
transition_matrix.masked_select(mask != 0).sum()

tensor(-17.7631)

In [48]:
torch.exp(transition_matrix)

tensor([[[0.0286, 0.7332, 0.2382],
         [0.5581, 0.3270, 0.1149],
         [0.7018, 0.1544, 0.1438]],

        [[0.3688, 0.5570, 0.0742],
         [0.6942, 0.1065, 0.1993],
         [0.3039, 0.3193, 0.3768]]])