In [82]:
import torch

In [83]:
# set seed for reproducibility
torch.manual_seed(0)

In [84]:
batch_size = 2
target_len = 3
vertices = 4

In [85]:
dp = torch.tensor([
    [
        [0.9, 0.1, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
    ],[
        [1, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
    ]
]).float()

In [86]:
transition_matrix = torch.randn(batch_size, vertices, vertices)
transition_matrix = torch.softmax(transition_matrix, dim=-1)

In [87]:
dp

tensor([[[0.9000, 0.1000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[1.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]]])

In [88]:
transition_matrix[:, 0, 0] = 0

In [89]:
transition_matrix

tensor([[[0.0000, 0.1529, 0.3766, 0.3136],
         [0.4507, 0.3854, 0.1406, 0.0233],
         [0.3107, 0.0636, 0.3194, 0.3063],
         [0.1340, 0.4099, 0.3632, 0.0928]],

        [[0.0000, 0.0415, 0.3991, 0.5008],
         [0.1995, 0.0232, 0.0779, 0.6994],
         [0.4489, 0.1181, 0.1783, 0.2547],
         [0.3370, 0.4104, 0.2164, 0.0361]]])

In [90]:
dp[0][0, :]

tensor([0.9000, 0.1000, 0.0000, 0.0000])

In [94]:
0.1529 *0.9

0.13761

In [95]:
0.3854 * 0.1

0.038540000000000005

In [91]:
dp[0][0, :] @ transition_matrix[0]

tensor([0.0451, 0.1761, 0.3530, 0.2845])

In [92]:
(dp[0][0, :] * transition_matrix[0].T).T

tensor([[0.0000, 0.1376, 0.3390, 0.2822],
        [0.0451, 0.0385, 0.0141, 0.0023],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [97]:
maxv, maxi = torch.max(dp[0][0, :] * transition_matrix[0].T, dim=-1)

In [98]:
maxv

tensor([0.0451, 0.1376, 0.3390, 0.2822])

In [99]:
# now do equivalent in log space
dp = torch.log(dp)
transition_matrix = torch.log(transition_matrix)

In [100]:
maxv, maxi = torch.max(dp[0][0, :] + transition_matrix[0].T, dim=-1)

In [101]:
maxv

tensor([-3.0995, -1.9836, -1.0818, -1.2651])

In [102]:
torch.exp(maxv)

tensor([0.0451, 0.1376, 0.3390, 0.2822])

In [103]:
maxi

tensor([1, 0, 0, 0])