In [60]:
import torch
from torch.nn.functional import log_softmax, softmax

In [61]:
a = torch.tensor([1, 2])
e = torch.tensor([
    [
        2,5
    ],
    [
        6,7
    ]
])
b = torch.tensor([
    [
        4
    ],
    [5]
])

In [62]:
a @ e

tensor([14, 19])

In [63]:
b.T * (a @ e)

tensor([[56, 95]])

In [64]:
eLog = torch.log(e)
aLog = torch.log(a)

In [65]:
summed = aLog + eLog.T

In [66]:
summed

tensor([[0.6931, 2.4849],
        [1.6094, 2.6391]])

In [67]:
torch.exp(summed)

tensor([[ 2.0000, 12.0000],
        [ 5.0000, 14.0000]])

In [68]:
torch.exp(torch.logsumexp(summed, dim=-1))

tensor([14.0000, 19.0000])

In [69]:
logAE = torch.logsumexp(summed, dim=-1)
logB = torch.log(b)

In [72]:
torch.exp(logB.T + logAE)

tensor([[56.0000, 95.0000]])

In [73]:
b.T * (a @ e)

tensor([[56, 95]])