In [19]:
import torch

In [20]:
seq_len = 5
batch_size = 3
vocab_size = 6 # 0-5, actual vocab size is 7 when including padding
pad_idx = 6
seq_len_padded = seq_len + 2

In [21]:
tokens = []
for i in range(batch_size):
    sampled_len = torch.randint(1, seq_len, (1,)).item()
    tokens.append(torch.randint(1, vocab_size, (sampled_len,)))

In [22]:
tokens

[tensor([5]), tensor([3, 3, 4]), tensor([5, 3])]

In [23]:
tokens = torch.nested.nested_tensor(tokens)

In [24]:
tokens = torch.nested.to_padded_tensor(tokens, pad_idx, (batch_size, seq_len_padded))

In [25]:
tokens

tensor([[5, 6, 6, 6, 6, 6, 6],
        [3, 3, 4, 6, 6, 6, 6],
        [5, 3, 6, 6, 6, 6, 6]])

In [26]:
not_pad = tokens != pad_idx

In [27]:
not_pad

tensor([[ True, False, False, False, False, False, False],
        [ True,  True,  True, False, False, False, False],
        [ True,  True, False, False, False, False, False]])

In [28]:
# find all columns in `not_pad` that sum to 0 (i.e. all padding columns)
pad_cols = torch.where(not_pad.sum(dim=0) == 0)[0]

In [29]:
pad_cols

tensor([3, 4, 5, 6])

In [34]:
not_pad.any(dim=0)

tensor([ True,  True,  True, False, False, False, False])

In [30]:
# remove all padding columns
tokens = tokens[:, not_pad.any(dim=0)]

In [31]:
tokens

tensor([[5, 6, 6],
        [3, 3, 4],
        [5, 3, 6]])

In [2]:
import torch

# Define the batch size
batch_size = 3

# Create a list of tuples, each tuple representing a sample in the batch
mock_batch = [(torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6])),
              (torch.tensor([7, 8, 9]), torch.tensor([10, 11, 12])),
              (torch.tensor([13, 14, 15]), torch.tensor([16, 17, 18]))]


In [3]:
ens, zhs = zip(*mock_batch)

In [4]:
ens

(tensor([1, 2, 3]), tensor([7, 8, 9]), tensor([13, 14, 15]))

In [5]:
torch.stack(ens)

tensor([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]])