In [21]:
import torch

In [22]:
batch_size, seq_len, emb_dim = 2, 3, 4
vocab_size = 4
targets = torch.LongTensor([[0, 1, 3], [3, 1, 0]])

In [23]:
vocab_classifier_head = torch.nn.Linear(emb_dim, vocab_size)

In [24]:
test_hidden = torch.randn(batch_size, seq_len, emb_dim)

In [25]:
out = vocab_classifier_head(test_hidden)

In [26]:
out = torch.log_softmax(out, dim=-1)

In [27]:
out

tensor([[[-1.6254, -0.8939, -1.8896, -1.4148],
         [-1.2027, -1.0284, -2.2034, -1.4626],
         [-1.4087, -0.9212, -1.8281, -1.6256]],

        [[-1.4790, -1.1032, -1.8995, -1.2355],
         [-1.6267, -0.9354, -1.9520, -1.3130],
         [-1.7222, -0.8245, -1.4299, -1.9413]]], grad_fn=<LogSoftmaxBackward0>)

In [28]:
targets

tensor([[0, 1, 3],
        [3, 1, 0]])

In [33]:
torch.exp(out)

tensor([[[0.1968, 0.4091, 0.1511, 0.2430],
         [0.3004, 0.3576, 0.1104, 0.2316],
         [0.2445, 0.3980, 0.1607, 0.1968]],

        [[0.2279, 0.3318, 0.1497, 0.2907],
         [0.1966, 0.3924, 0.1420, 0.2690],
         [0.1787, 0.4385, 0.2393, 0.1435]]], grad_fn=<ExpBackward0>)

In [39]:
torch.exp(out)[0][0][0]

tensor(0.1968, grad_fn=<SelectBackward0>)

In [36]:
g = out.gather(dim=-1, index=targets.unsqueeze(1).expand(-1, seq_len, -1))

In [38]:
torch.exp(g)[0][0][0]

tensor(0.1968, grad_fn=<SelectBackward0>)

In [40]:
g

tensor([[[-1.6254, -0.8939, -1.4148],
         [-1.2027, -1.0284, -1.4626],
         [-1.4087, -0.9212, -1.6256]],

        [[-1.2355, -1.1032, -1.4790],
         [-1.3130, -0.9354, -1.6267],
         [-1.9413, -0.8245, -1.7222]]], grad_fn=<GatherBackward0>)

In [41]:
g.shape

torch.Size([2, 3, 3])

In [43]:
torch.chunk(g, seq_len, dim=-1)

(tensor([[[-1.6254],
          [-1.2027],
          [-1.4087]],
 
         [[-1.2355],
          [-1.3130],
          [-1.9413]]], grad_fn=<SplitBackward0>),
 tensor([[[-0.8939],
          [-1.0284],
          [-0.9212]],
 
         [[-1.1032],
          [-0.9354],
          [-0.8245]]], grad_fn=<SplitBackward0>),
 tensor([[[-1.4148],
          [-1.4626],
          [-1.6256]],
 
         [[-1.4790],
          [-1.6267],
          [-1.7222]]], grad_fn=<SplitBackward0>))

In [45]:
torch.chunk(g, seq_len, dim=-1)[0].shape

torch.Size([2, 3, 1])